### Introduction of Numpy:

Numpy stands for numerical python. The primary use of numpy is effiecient data handling and manipulation.

Numpy has inbuilt function for working with numpy object.


In [452]:
import numpy as np
import os

In [453]:
os.getcwd()

'C:\\Users\\AEPAC\\Desktop\\KnowledgeHut\\2024\\2024_upGrad\\Dec\\Python for NumPy (DS)'

In [2]:
np?

### Numpy Arrays:

In [3]:
np_arr = np.array()

TypeError: array() missing required argument 'object' (pos 0)

In [4]:
arr = np.array([])

In [5]:
arr

array([], dtype=float64)

In [6]:
type(arr)

numpy.ndarray

In [7]:
len(arr)

0

In [8]:
lst = [1,2,3,6]

In [9]:
arr = np.array(object = lst)

In [10]:
arr

array([1, 2, 3, 6])

In [11]:
arr.dtype

dtype('int32')

In [12]:
arr = np.array(['Apple','Orange','Banana','Watermelon','Jackfruit'])

In [13]:
arr

array(['Apple', 'Orange', 'Banana', 'Watermelon', 'Jackfruit'],
      dtype='<U10')

### Note:

Array is the collection of similar data type.

In [14]:
lst.index?

In [15]:
lst

[1, 2, 3, 6]

In [16]:
lst.index(6)

3

In [18]:
np.array?

In [19]:
lst.append?

In [20]:
lst.append("Abhishek")

In [21]:
arr = np.array([1,5,7,8,10.25])

In [22]:
arr

array([ 1.  ,  5.  ,  7.  ,  8.  , 10.25])

In [23]:
arr = np.array([1,4,6,7,'ABC'])

In [24]:
arr

array(['1', '4', '6', '7', 'ABC'], dtype='<U11')

In [25]:
tp = (0,5,7,9,0,4)

In [26]:
np.array(tp)

array([0, 5, 7, 9, 0, 4])

In [27]:
setA = {1.5,6,8,-8.5}

In [28]:
np.array(setA)

array({8, 1.5, 6, -8.5}, dtype=object)

### Multidimensional arrays:

In [29]:
lst

[1, 2, 3, 6, 'Abhishek']

In [30]:
np.array([2,3,4,5,-10])

array([  2,   3,   4,   5, -10])

In [31]:
arr_2d = np.array([[1,2,3],[4,5,6]])

In [32]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr_3d = np.array([[[1,5],[3,4],[5,6],[7,9],[8,9]]])

In [34]:
arr_3d

array([[[1, 5],
        [3, 4],
        [5, 6],
        [7, 9],
        [8, 9]]])

In [35]:
arr

array(['1', '4', '6', '7', 'ABC'], dtype='<U11')

In [36]:
a = "Priyanka"

In [37]:
arr.ndim

1

In [38]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr_2d.ndim

2

In [40]:
arr_3d.ndim

3

In [41]:
arr

array(['1', '4', '6', '7', 'ABC'], dtype='<U11')

In [42]:
arr.shape

(5,)

In [43]:
arr_2d.shape

(2, 3)

In [44]:
arr_3d.shape

(1, 5, 2)

In [60]:
arr1 = np.array(['1', '2', '3', 'Testsjflk', '1', '2', '3', 
                 '1', '2', '3', '1', '2', '3'], dtype='<U11')

In [61]:
arr1

array(['1', '2', '3', 'Testsjflk', '1', '2', '3', '1', '2', '3', '1', '2',
       '3'], dtype='<U11')

In [62]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arr_2d.shape

(2, 3)

In [64]:
arr_2d.size

6

In [65]:
arr = np.array([22,-36,32,47,71,-45])

In [66]:
arr

array([ 22, -36,  32,  47,  71, -45])

In [67]:
arr[1]

-36

In [68]:
arr[1:4]

array([-36,  32,  47])

In [69]:
arr[[1,2,3]]

array([-36,  32,  47])

In [70]:
arr

array([ 22, -36,  32,  47,  71, -45])

In [71]:
arr[2:]

array([ 32,  47,  71, -45])

In [72]:
arr[:3]

array([ 22, -36,  32])

In [73]:
arr[::-1]

array([-45,  71,  47,  32, -36,  22])

In [74]:
arr

array([ 22, -36,  32,  47,  71, -45])

In [75]:
arr[1:-1]

array([-36,  32,  47,  71])

In [77]:
arr[1:len(arr)-1]

array([-36,  32,  47,  71])

In [78]:
arr

array([ 22, -36,  32,  47,  71, -45])

In [79]:
lst = [22,-36,32,47,71,-45]

In [80]:
lst[1:-1]

[-36, 32, 47, 71]

In [81]:
lst[:3]

[22, -36, 32]

In [82]:
lst[1:4]

[-36, 32, 47]

In [86]:
arr = np.array([['Python','R','C++'], [len('Python'),len('R'), 
                                       len('C++')]])

In [87]:
arr

array([['Python', 'R', 'C++'],
       ['6', '1', '3']], dtype='<U11')

In [88]:
len(arr)

2

In [89]:
arr[0][0]

'Python'

In [90]:
arr[0,0]

'Python'

In [91]:
arr[0]

array(['Python', 'R', 'C++'], dtype='<U11')

In [92]:
arr[0].shape

(3,)

In [93]:
arr[[0]].shape

(1, 3)

In [94]:
arr

array([['Python', 'R', 'C++'],
       ['6', '1', '3']], dtype='<U11')

In [96]:
arr[0,0]

'Python'

In [97]:
arr[0][0]

'Python'

In [98]:
arr[0:]

array([['Python', 'R', 'C++'],
       ['6', '1', '3']], dtype='<U11')

In [99]:
arr[0][:]

array(['Python', 'R', 'C++'], dtype='<U11')

In [100]:
arr[0,[0,1]]

array(['Python', 'R'], dtype='<U11')

In [101]:
lst

[22, -36, 32, 47, 71, -45]

In [102]:
lst[0:]

[22, -36, 32, 47, 71, -45]

In [103]:
arr[0:]

array([['Python', 'R', 'C++'],
       ['6', '1', '3']], dtype='<U11')

In [104]:
arr.shape

(2, 3)

In [105]:
arr.ndim

2

In [106]:
lst = [[1,2,3],[4,5,6]]

In [107]:
lst

[[1, 2, 3], [4, 5, 6]]

In [108]:
len(lst)

2

In [109]:
lst[1]

[4, 5, 6]

In [110]:
lst[0]

[1, 2, 3]

In [111]:
lst[0:]

[[1, 2, 3], [4, 5, 6]]

In [112]:
lst[0:0]

[]

In [113]:
lst[0][:]

[1, 2, 3]

In [114]:
lst[-1][:]

[4, 5, 6]

In [115]:
arr = np.array([[1,2,3],[4,5,6]])

In [116]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
arr > 2

array([[False, False,  True],
       [ True,  True,  True]])

In [120]:
# False : 0
# True : 1

In [121]:
sum(arr)

array([5, 7, 9])

In [122]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [133]:
df['Order Date'].isna().sum()

8

In [134]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
(arr > 2) & (arr < 5)

array([[False, False,  True],
       [ True, False, False]])

In [139]:
arr[(arr > 2) |(arr < 5)]

array([1, 2, 3, 4, 5, 6])

In [141]:
arr_numbers = np.array([34,56,87,90,34,56,12,34,67,89,90,88,
                      35,67,12,45,78,23,56])

In [142]:
lst = [34,56,87,90,34,56,12,34,67,89,90,88,35,67,12,45,78,23,56]

In [143]:
list(filter(lambda x : x > 50, lst))

[56, 87, 90, 56, 67, 89, 90, 88, 67, 78, 56]

In [144]:
arr_numbers

array([34, 56, 87, 90, 34, 56, 12, 34, 67, 89, 90, 88, 35, 67, 12, 45, 78,
       23, 56])

In [146]:
len(arr_numbers > 50)

19

In [147]:
arr_numbers[arr_numbers > 50]

array([56, 87, 90, 56, 67, 89, 90, 88, 67, 78, 56])

In [148]:
len(arr_numbers[arr_numbers > 50])

11

In [149]:
arr_numbers

array([34, 56, 87, 90, 34, 56, 12, 34, 67, 89, 90, 88, 35, 67, 12, 45, 78,
       23, 56])

In [150]:
arr_numbers[arr_numbers % 2 == 0]

array([34, 56, 90, 34, 56, 12, 34, 90, 88, 12, 78, 56])

In [151]:
arr_numbers[arr_numbers % 2 != 0]

array([87, 67, 89, 35, 67, 45, 23])

In [152]:
arr_numbers[arr_numbers % 5 == 0]

array([90, 90, 35, 45])

In [153]:
len(arr_numbers)

19

### numpy where method

In [154]:
arr_numbers

array([34, 56, 87, 90, 34, 56, 12, 34, 67, 89, 90, 88, 35, 67, 12, 45, 78,
       23, 56])

In [155]:
np.where(arr_numbers < 50)

(array([ 0,  4,  6,  7, 12, 14, 15, 17], dtype=int64),)

In [156]:
np.where(arr_numbers == 90)

(array([ 3, 10], dtype=int64),)

In [157]:
np.where((arr_numbers >50) & (arr_numbers < 60))

(array([ 1,  5, 18], dtype=int64),)

In [158]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [159]:
np.where(arr_2d > 3)

(array([1, 1, 1], dtype=int64), array([0, 1, 2], dtype=int64))

In [161]:
arr_2d > 3

array([[False, False, False],
       [ True,  True,  True]])

In [162]:
arr_2d[np.where(arr_2d > 3)]

array([4, 5, 6])

In [163]:
arr_numbers

array([34, 56, 87, 90, 34, 56, 12, 34, 67, 89, 90, 88, 35, 67, 12, 45, 78,
       23, 56])

In [164]:
np.where((arr_numbers < 50),"<50", arr_numbers)

array(['<50', '56', '87', '90', '<50', '56', '<50', '<50', '67', '89',
       '90', '88', '<50', '67', '<50', '<50', '78', '<50', '56'],
      dtype='<U11')

### Operations on Numpy Arrays:

In [172]:
np_arr = np.array([1,2,3])

In [173]:
np_arr

array([1, 2, 3])

### Adding elements to 1D array

In [174]:
np.append(arr = np_arr, values = 4)

array([1, 2, 3, 4])

In [175]:
np.append(np_arr,4)

array([1, 2, 3, 4])

In [176]:
np.append(np_arr,[5,6,7,8,9])

array([1, 2, 3, 5, 6, 7, 8, 9])

### Removing elements from 1d arrays

In [177]:
np_arr

array([1, 2, 3])

### numpy delete method

This method can delete an item based on item's index.

In [178]:
np.delete(np_arr, 2)

array([1, 2])

In [179]:
print([i for i in dir(list) if "__" not in i])

['append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [182]:
arr_numbers

array([34, 56, 87, 90, 34, 56, 12, 34, 67, 89, 90, 88, 35, 67, 12, 45, 78,
       23, 56])

In [183]:
np.delete(arr_numbers,[0,-1])

array([56, 87, 90, 34, 56, 12, 34, 67, 89, 90, 88, 35, 67, 12, 45, 78, 23])

In [184]:
np.delete(arr_numbers, np.where(arr_numbers % 2 == 0))

array([87, 67, 89, 35, 67, 45, 23])

In [185]:
np_arr1 = np.array([[4.7,1.4,-4.6],[2.6,-1.2,-2],[6.6,-3.2,4.9]])

In [186]:
np_arr1

array([[ 4.7,  1.4, -4.6],
       [ 2.6, -1.2, -2. ],
       [ 6.6, -3.2,  4.9]])

In [187]:
np.delete(np_arr1, 0)

array([ 1.4, -4.6,  2.6, -1.2, -2. ,  6.6, -3.2,  4.9])

In [188]:
np.delete(np_arr1, 0, axis = 0)

array([[ 2.6, -1.2, -2. ],
       [ 6.6, -3.2,  4.9]])

In [190]:
np.delete(np_arr1, [0-1], axis = 0)

array([[ 4.7,  1.4, -4.6],
       [ 2.6, -1.2, -2. ]])

In [191]:
np.delete(np_arr1,[0,1], axis = 0)

array([[ 6.6, -3.2,  4.9]])

In [192]:
np_arr1

array([[ 4.7,  1.4, -4.6],
       [ 2.6, -1.2, -2. ],
       [ 6.6, -3.2,  4.9]])

In [193]:
np.delete(np_arr1, 1,axis = 1)

array([[ 4.7, -4.6],
       [ 2.6, -2. ],
       [ 6.6,  4.9]])

In [203]:
lst.extend?

In [204]:
filter?

In [215]:
lst = [2,5,7,None,"",34,56,False,60,0,False,True,-50, None,40,60, None]

In [216]:
list(filter(None,lst))

[2, 5, 7, 34, 56, 60, True, -50, 40, 60]

In [ ]:
axis = None,
axis = 0
axis = 1

In [211]:
np_arr1

array([[ 4.7,  1.4, -4.6],
       [ 2.6, -1.2, -2. ],
       [ 6.6, -3.2,  4.9]])

In [212]:
np.delete(np_arr1, 0, axis = None)

array([ 1.4, -4.6,  2.6, -1.2, -2. ,  6.6, -3.2,  4.9])

In [214]:
np.delete(np_arr1, [0,-1],axis = 1)

array([[ 1.4],
       [-1.2],
       [-3.2]])

In [217]:
np_arr1

array([[ 4.7,  1.4, -4.6],
       [ 2.6, -1.2, -2. ],
       [ 6.6, -3.2,  4.9]])

In [225]:
np.delete(np.delete(np_arr1, 0, axis = 0), 0, axis = 1)

array([[-1.2, -2. ],
       [-3.2,  4.9]])

In [226]:
lst

[2, 5, 7, None, '', 34, 56, False, 60, 0, False, True, -50, None, 40, 60, None]

In [227]:
lst.append(7)

In [228]:
lst.append(5)

In [229]:
lst.extend([5,6,7,8,3,5,7,0,7])

In [230]:
print(lst)

[2, 5, 7, None, '', 34, 56, False, 60, 0, False, True, -50, None, 40, 60, None, 7, 5, 5, 6, 7, 8, 3, 5, 7, 0, 7]


In [232]:
lst.index(7)

2

In [233]:
lst.index(7, 2+1)

17

In [234]:
lst[17]

7

In [235]:
lst.index(7,17+1)

21

In [237]:
for pair in enumerate(lst):
    if pair[-1] == 7:
        print(pair[0], end = " ")


2 17 21 25 27 

### How to generate random numbers

In [267]:
np.random.randint(low = 10, high = 99, size = 50)

array([17, 37, 22, 47, 31, 93, 92, 30, 11, 10, 74, 91, 72, 76, 33, 21, 56,
       32, 67, 62, 80, 89, 23, 66, 78, 84, 86, 75, 92, 21, 63, 15, 83, 67,
       15, 23, 16, 92, 29, 16, 97, 83, 95, 97, 14, 72, 10, 39, 87, 67])

In [243]:
np.random.rand(20)

array([0.65260198, 0.26751268, 0.10435632, 0.21925879, 0.68762057,
       0.79200452, 0.66055733, 0.95952961, 0.83449451, 0.26859558,
       0.17126075, 0.02366749, 0.58841728, 0.27812057, 0.25396988,
       0.30453645, 0.21383576, 0.94616023, 0.39367805, 0.35975746])

In [263]:
min(np.random.randn(100))

-2.31163869350953

In [246]:
np.random.randn?

In [271]:
np.random.randint(low = 10, high = 99, size = 50)

array([10, 79, 73, 12, 13, 82, 75, 33, 57, 72, 38, 78, 49, 47, 73, 83, 30,
       82, 55, 89, 58, 32, 57, 37, 63, 71, 90, 68, 36, 94, 85, 67, 15, 43,
       63, 54, 29, 10, 35, 68, 57, 75, 71, 90, 31, 74, 48, 29, 73, 50])

### Numpy Seed

Whenever you are working on numbers and you are performing any x,y,z analysis on your dataset and the same data you want in your system.

In [277]:
np.random.seed(10)
np.random.randint(low = 10, high = 99, size = 50)

array([19, 25, 74, 38, 39, 18, 83, 10, 50, 46, 26, 21, 64, 98, 72, 43, 82,
       88, 59, 61, 64, 87, 79, 23, 35, 23, 96, 40, 40, 22, 75, 41, 67, 46,
       37, 28, 87, 32, 33, 21, 38, 84, 98, 19, 25, 28, 90, 81, 98, 21])

In [278]:
np.random.seed(11)
np.random.randint(low = 10, high = 99, size = 50)

array([35, 73, 90, 91, 65, 23, 86, 43, 81, 92, 34, 58, 42, 55, 14, 44, 22,
       11, 84, 47, 94, 91, 34, 27, 77, 80, 53, 74, 89, 33, 37, 80, 20, 67,
       37, 54, 24, 17, 65, 89, 74, 50, 37, 15, 63, 81, 60, 69, 11, 13])

In [279]:
np.random.seed(42)
np.random.randint(low = 10, high = 99, size = 50)

array([61, 24, 81, 70, 30, 92, 96, 84, 84, 97, 33, 12, 31, 62, 11, 97, 39,
       47, 11, 73, 69, 30, 42, 85, 67, 31, 98, 58, 68, 51, 69, 89, 24, 71,
       71, 56, 71, 60, 64, 73, 12, 60, 16, 30, 82, 48, 27, 13, 98, 69])

In [280]:
np.random.seed(100)
np.random.randint(low = 10, high = 99, size = 50)

array([18, 34, 77, 97, 89, 58, 20, 62, 63, 76, 24, 44, 34, 25, 70, 68, 26,
       19, 96, 12, 37, 14, 41, 11, 23, 93, 14, 69, 77, 17, 59, 57, 75, 71,
       24, 65, 81, 90, 12, 29, 73, 63, 37, 66, 40, 58, 57, 49, 48, 54])

In [281]:
np.random.seed(10000)
np.random.randint(low = 10, high = 99, size = 50)

array([22, 63, 41, 50, 57, 12, 31, 82, 71, 27, 80, 82, 95, 64, 49, 44, 72,
       85, 61, 86, 24, 25, 17, 82, 53, 51, 84, 44, 36, 54, 45, 87, 40, 16,
       87, 68, 56, 98, 14, 88, 89, 92, 95, 90, 70, 65, 50, 96, 78, 37])

In [288]:
np.random.seed(10)
np.random.randint(10,1000,5)

array([275, 135, 537, 330, 379])

### Concatenating and Splitting arrays:

In [304]:
arr1 = np.array([[1,2],[-4,3],[2,-5]])

In [305]:
arr1

array([[ 1,  2],
       [-4,  3],
       [ 2, -5]])

In [308]:
arr2 = np.array([[1,2],[-4,3],[2,-5]])
arr2

array([[ 1,  2],
       [-4,  3],
       [ 2, -5]])

In [307]:
np.concatenate((arr1,arr2))

array([[ 1,  2],
       [-4,  3],
       [ 2, -5],
       [ 1,  2],
       [-4,  3],
       [ 2, -5]])

In [309]:
np.concatenate((arr1,arr2), axis = 0)

array([[ 1,  2],
       [-4,  3],
       [ 2, -5],
       [ 1,  2],
       [-4,  3],
       [ 2, -5]])

In [310]:
np.concatenate((arr1,arr2), axis = 1)

array([[ 1,  2,  1,  2],
       [-4,  3, -4,  3],
       [ 2, -5,  2, -5]])

In [311]:
arr3 = np.concatenate((arr1,arr2), axis = 1)
arr3

array([[ 1,  2,  1,  2],
       [-4,  3, -4,  3],
       [ 2, -5,  2, -5]])

In [313]:
np.split(ary = arr3, indices_or_sections=[1])

[array([[1, 2, 1, 2]]),
 array([[-4,  3, -4,  3],
        [ 2, -5,  2, -5]])]

### Arithematic Operations:

In [314]:
revenue_nov = np.array([3485.09, 2784.89, 1930.80])
revenue_dec = np.array([4859.90,1800.00,4500.50])

In [315]:
revenue_nov + revenue_dec

array([8344.99, 4584.89, 6431.3 ])

In [316]:
total_revenue = revenue_nov + revenue_dec

In [317]:
total_revenue

array([8344.99, 4584.89, 6431.3 ])

In [318]:
revenue_nov + 50

array([3535.09, 2834.89, 1980.8 ])

In [319]:
revenue_nov - 50

array([3435.09, 2734.89, 1880.8 ])

In [320]:
revenue_nov / 2

array([1742.545, 1392.445,  965.4  ])

In [321]:
revenue_nov * 2

array([6970.18, 5569.78, 3861.6 ])

In [322]:
v1 = np.array([[5,-4],[-3,2]])
v2 = np.array([[3,8],[-6,0]])

In [323]:
v1

array([[ 5, -4],
       [-3,  2]])

In [324]:
v2

array([[ 3,  8],
       [-6,  0]])

In [325]:
v1 + v2

array([[ 8,  4],
       [-9,  2]])

In [326]:
v1 - v2

array([[  2, -12],
       [  3,   2]])

In [327]:
v1

array([[ 5, -4],
       [-3,  2]])

In [329]:
sum_arr = v1 + 8

In [332]:
sum_arr[0] + 3


array([16,  7])

In [333]:
sum_arr

array([[13,  4],
       [ 5, 10]])

In [334]:
sum_arr[0] = sum_arr[0] + 3
sum_arr

array([[16,  7],
       [ 5, 10]])

### Numpy provides set operations  as follows:

* setdiff1d
* intersection1d

In [335]:
x = np.array([4,5,6,7,8,9,0])
y = np.array([4,5,1,8,12])

In [336]:
np.setdiff1d(x,y)

array([0, 6, 7, 9])

In [337]:
np.setdiff1d(y,x)

array([ 1, 12])

In [338]:
np.intersect1d(x,y)

array([4, 5, 8])

In [340]:
x

array([4, 5, 6, 7, 8, 9, 0])

In [341]:
y

array([ 4,  5,  1,  8, 12])

In [339]:
np.intersect1d(x,y, return_indices=True)

(array([4, 5, 8]),
 array([0, 1, 4], dtype=int64),
 array([0, 1, 3], dtype=int64))

### Mathematical and Statistical Function in numpy

In [342]:
x1 = np.array([1,2,3])
x2 = np.array([2,2,2])

In [343]:
np.add(x1,x2)

array([3, 4, 5])

In [344]:
np.subtract(x1,x2)

array([-1,  0,  1])

In [345]:
np.multiply(x1,x2)

array([2, 4, 6])

In [346]:
np.power(x1,2)

array([1, 4, 9], dtype=int32)

In [347]:
np.sqrt(x2)

array([1.41421356, 1.41421356, 1.41421356])

In [348]:
x1

array([1, 2, 3])

In [349]:
x2

array([2, 2, 2])

In [350]:
np.divmod(x1,x2)

(array([0, 1, 1]), array([1, 0, 1]))

In [351]:
y

array([ 4,  5,  1,  8, 12])

In [354]:
y = np.append(y,11)

In [355]:
y

array([ 4,  5,  1,  8, 12, 11])

In [356]:
x

array([4, 5, 6, 7, 8, 9, 0])

In [358]:
x1 = np.array([10,20,30])
x2 = np.array([5,6,6])

In [359]:
np.divmod(x1,x2)

(array([2, 3, 5]), array([0, 2, 0]))

In [360]:
quotient, remainder = np.divmod(x1,x2)

In [361]:
quotient

array([2, 3, 5])

In [362]:
remainder

array([0, 2, 0])

In [363]:
np.divide(x1,x2)

array([2.        , 3.33333333, 5.        ])

In [364]:
np.floor_divide(x1,x2)

array([2, 3, 5])

In [365]:
np.mod(x1,x2)

array([0, 2, 0])

In [380]:
arr = np.random.randint(10,100,40)

In [381]:
arr

array([33, 21, 38, 84, 98, 19, 25, 28, 90, 81, 98, 21, 27, 56, 17, 85, 38,
       43, 94, 98, 54, 15, 14, 81, 98, 98, 60, 64, 44, 25, 87, 98, 25, 16,
       95, 32, 21, 22, 72, 67])

In [382]:
np.mean(arr)

54.55

In [383]:
np.sum(arr)

2182

In [384]:
np.average(arr)

54.55

In [385]:
np.std(arr)

30.926485412991887

In [386]:
np.median(arr)

49.0

In [387]:
np.percentile(arr,0.25)

14.0975

In [388]:
print(arr)

[33 21 38 84 98 19 25 28 90 81 98 21 27 56 17 85 38 43 94 98 54 15 14 81
 98 98 60 64 44 25 87 98 25 16 95 32 21 22 72 67]


In [400]:
arr1 = np.array([4,np.nan,5,6,np.nan,5,10,np.nan])

In [401]:
arr1

array([ 4., nan,  5.,  6., nan,  5., 10., nan])

In [402]:
sum(arr)

nan

In [403]:
max(arr)

10.0

In [404]:
min(arr)

4.0

In [405]:
np.mean(arr1)

nan

In [406]:
np.std(arr1)

nan

In [407]:
arr

array([ 4.,  5.,  6., nan,  5., 10., nan])

In [408]:
np.nansum(arr)

30.0

In [409]:
np.nanmean(arr)

6.0

In [411]:
np.nanpercentile(arr,0.25)

4.01

In [412]:
np.nanmax(arr)

10.0

In [413]:
print("All the function from numpy: ",
     [i for i in dir(np) if "__" not in i])

All the function from numpy:  ['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '_add_newdoc_ufunc', '_builtins', '_core', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_typing', '_using_numpy2_behavior', '_utils', 'abs', 'absolute', 'add', 'add_docstring', 'add_newdoc', 'add_newdoc_ufunc', 'all', 'allclo

In [420]:
# print("All the methods form list: ", [i for i in dir(list) if "__" not in i])
# print()
# print("All the methods form tuple: ", [i for i in dir(tuple) if "__" not in i])
# print()
# print("All the methods form set: ", [i for i in dir(set) if "__" not in i])

# print()
# print("All the methods form dict: ", [i for i in dir(dict) if "__" not in i])
# print()
# print("All the methods form str: ", [i for i in dir(str) if "__" not in i])


In [419]:
# print(dir(__builtins__))

In [425]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [427]:
np.arange(60).reshape(2,6,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [429]:
arr = np.arange(30).reshape(6,5)

In [430]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [431]:
arr.sum()

435

In [432]:
arr.sum(axis=0)

array([75, 81, 87, 93, 99])

In [433]:
arr.sum(axis=1)

array([ 10,  35,  60,  85, 110, 135])

In [435]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [440]:
arr[0][0] = 1

In [445]:
arr

array([[ 1,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [447]:
arr.prod(axis=0)

array([ 375000,  576576, 1696464, 3616704, 6664896])

In [448]:
arr.prod(axis=1)

array([      24,    15120,   240240,  1395360,  5100480, 14250600])

In [449]:
arr.mean()

14.533333333333333

In [450]:
arr.mean(axis=0)

array([12.66666667, 13.5       , 14.5       , 15.5       , 16.5       ])

In [451]:
arr.mean(axis=1)

array([ 2.2,  7. , 12. , 17. , 22. , 27. ])